# Generated by Django 5.1.4 on 2025-01-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
